### ISSUE TITLE
Refactor all the thing

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Confort-plus#78]
Project architecture is kinda outdated now, using Grunt on a Yeoman boilerplate through Bower for Node10… 

We need to upgrade the project architecture to ease maintenance, contribution and evolution—but also to fix #75, #73 and #59, for example (maybe  #71 too, by the way).

However it needs a plan! Here we go.

## Requirements

- [x] Drop Bower entirely: #79 
- [x] Drop IE11 Add-on: #83
- [x] ~Drop server version~: still useful.
- [ ] Drop Grunt, switching to npm scripts: this require a deep understanding of what's actually going on with current Grunt scripts: #85 

 ## Improvements

- [x] Add `.editorconfig` at least, 
- And linters at some point → #89
- Add a zip script to package WebExtension → #90
- Allow npm publication for server version → #86
- Automate changelog (based on conventionnal-commit tooling, like on Boosted) → #91
- Update Netlify configuration and deployments → #92
- deploy docs from `/docs` folder and drop `gh-pages` branch → #92
  - needs some cleanup from `gh-pages`, which is quite messy right now…
-  use GitHub Actions at some point to run tests and/or deploy a preview on Netlify → #93
- improve documentation website (probably another topic, but hey… who knows?): use 11ty or something? → #94
- optimize images: using SVGO, but also imgmin — and use modern image format like webp? → #95
- Refactor HTML & CSS → #96
- Refactor JavaScript … #97

Anything else?
